export const SET_USER_LIST = "SET_USER_LIST";
export const SET_LOADER = "SET_LOADER";
export const SET_USER_DATA = "SET_USER_DATA";
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const SET_LOGIN_DATA = "SET_LOGIN_DATA";

export const SET_PRODUCT_LIST="SET_PRODUCT_LIST";
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const DELETE_PRODUCT_DATA = "DELETE_PRODUCT_DATA";
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";

export const SET_CATEGORY_LIST="SET_CATEGORY_LIST";

export const SET_SUBCATEGORY_LIST="SET_SUBCATEGORY_LIST";
